services:
  server:
    build:
      context: ./server
      dockerfile: ./server/Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server/:/app/
    working_dir: /app/
  client:
    build:
      context: ./client
      dockerfile: ./client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - server
