"""Create relation between author and quote

Revision ID: 213c47533f59
Revises: f0f5fb5e081e
Create Date: 2025-03-24 09:35:18.566520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213c47533f59'
down_revision: Union[str, None] = 'f0f5fb5e081e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quotes', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'author_id')
    # ### end Alembic commands ###
